### ISSUE TITLE
Subdomains pass through

### ISSUE THREAD

**Issue by whatsnewsisyphus** [dguo/pawblock#2]
Hello,
Thanks a lot for the extension, just one request, currently, subdomains pass through. You can go to smile.amazon.com if you block amazon.com for example. Since it doesn't accept * as a wildcard, it would be nice to add a little box that says include all subdomains or something of the sort.

**Comment by dguo** [comment]
Thanks for the feedback. I had considered just letting the user enter a regex, but I wanted to keep it as simple as possible. There should be a way to block the subdomain though. I'll try to find time this weekend to make the change.

**Comment by dguo** [comment]
I've submitted a new version to the Chrome and Firefox stores. In the new version, the rules are treated as regexes. So the subdomain issue is taken care of because a regex made from `amazon.com` will match both `amazon.com` and `smile.amazon.com`.

People without programming experience won't be familiar with regexes, but the default behavior is better anyway since I think most people would expect subdomains to be blocked. And at least with regexes, we aren't creating an ad hoc wild card system.

Once the new versions are approved, users should get the new version once their installation is autoupdated (assuming they didn't turn autoupdate off).

**Comment by dguo** [comment]
I have the new versions now in both Firefox and Chrome. Subdomains should be blocked without the user having to do anything.
